; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards

[env:tny-360]
platform = espressif32@7.0.0
board = TNY-360_ESP32-S3_N16R8
framework = espidf
monitor_speed = 115200

extra_scripts = 
    pre:copy_web_assets.py # Copy web assets to /data before building LittleFS image
    pre:build_version.py # Inject build version information

board_build.partitions = partitions.csv
board_build.filesystem = littlefs

board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.embed_txtfiles = src/certs/root_ca.pem